font:
    normal:
        family: 'Go Mono'
        style: Normal

    bold:
        family: 'Go Mono'
        style: Bold

    italic:
        family: 'Go Mono'
        style: Italic

    bold_italic:
        family: 'Go Mono'
        style: Bold Italic

    size: 10

colors:
    primary:
        # background: '#000000'
        # foreground: '#FFFFFF'
        background: '#e8e2cc'
        foreground: '#444444'

            # normal:
            #     black:   '#000000'
            #     red:     '#cd0000'
            #     green:   '#00cd00'
            #     yellow:  '#cdcd00'
            #     blue:    '#0000ee'
            #     magenta: '#cd00cd'
            #     cyan:    '#00cdcd'
            #     white:   '#e5e5e5'

            # bright:
            #     black:   '#7f7f7f'
            #     red:     '#ff0000'
            #     green:   '#00ff00'
            #     yellow:  '#ffff00'
            #     blue:    '#5c5cff'
            #     magenta: '#ff00ff'
            #     cyan:    '#00ffff'
            #     white:   '#ffffff'

    normal:
        black:   '#444444'
        red:     '#dc322f'
        green:   '#859900'
        yellow:  '#b58900'
        blue:    '#268bd2'
        magenta: '#d33682'
        cyan:    '#2aa198'
        white:   '#d9d7cc'

    bright:
        black:   '#333333'
        red:     '#cd4b16'
        green:   '#93a1a1'
        yellow:  '#839496'
        blue:    '#657b83'
        magenta: '#6c71c4'
        cyan:    '#586e75'
        white:   '#e5e5e5'
